//! LLM-powered semgrep rule synthesis (MoCQ paper: [arxiv:2504.16057](https://arxiv.org/abs/2504.16057))
//!
//! Generates semgrep YAML rules from CWE identifiers using LLM synthesis,
//! validates them via `semgrep --validate`, and persists valid rules.

mod prompt;
mod validator;

pub use validator::{validate_rule, RuleError};

use crate::config::RuleSynthConfig;
use crate::llm::LlmClient;
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

/// A semgrep rule generated by the LLM
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SemgrepRule {
    pub id: String,
    pub language: String,
    pub yaml: String,
}

/// Rule synthesizer that generates semgrep rules from CWE identifiers
pub struct RuleSynthesizer<'a> {
    client: &'a LlmClient,
    config: &'a RuleSynthConfig,
}

impl<'a> RuleSynthesizer<'a> {
    /// Create a new rule synthesizer
    pub fn new(client: &'a LlmClient, config: &'a RuleSynthConfig) -> Self {
        Self { client, config }
    }

    /// Generate semgrep rules for a given CWE and language
    ///
    /// Returns only rules that pass `semgrep --validate`
    pub async fn generate(&self, cwe: &str, language: &str) -> Result<Vec<SemgrepRule>, RuleError> {
        // Build prompt
        let prompt = prompt::build_prompt(cwe, language, self.config.max_rules_per_cwe);

        // Call LLM
        let messages = vec![crate::llm::ChatMessage::user(&prompt)];
        let response = self
            .client
            .chat(&messages)
            .await
            .map_err(|e| RuleError::LlmError(e.to_string()))?;

        // Parse YAML rules from response
        let yaml_content = response.content;
        let rules = self.parse_yaml_rules(&yaml_content, language)?;

        // Validate each rule and collect valid ones
        let mut valid_rules = Vec::new();
        for (i, rule_yaml) in rules.into_iter().enumerate() {
            match validate_rule(&rule_yaml) {
                Ok(()) => {
                    // Extract rule ID from YAML
                    let rule_id =
                        extract_rule_id(&rule_yaml).unwrap_or_else(|| format!("cwe-{}-{}", cwe, i));

                    valid_rules.push(SemgrepRule {
                        id: rule_id,
                        language: language.to_string(),
                        yaml: rule_yaml,
                    });
                }
                Err(e) => {
                    tracing::warn!("Generated rule {} failed validation: {}", i, e);
                }
            }
        }

        // Persist valid rules
        if !valid_rules.is_empty() {
            self.persist_rules(&valid_rules, cwe, language)?;
        }

        Ok(valid_rules)
    }

    /// Parse YAML rules from LLM response
    fn parse_yaml_rules(
        &self,
        yaml_content: &str,
        _language: &str,
    ) -> Result<Vec<String>, RuleError> {
        let mut rules = Vec::new();
        let mut current_rule = String::new();
        let mut in_rule = false;

        for line in yaml_content.lines() {
            if line.trim() == "---" {
                if !current_rule.is_empty() {
                    rules.push(current_rule.trim().to_string());
                    current_rule = String::new();
                }
                in_rule = true;
                continue;
            }

            if in_rule || line.trim().starts_with("rules:") {
                let should_add = !current_rule.is_empty() || !line.trim().is_empty();
                if should_add {
                    current_rule.push_str(line);
                    current_rule.push('\n');
                }
            }
        }

        // Push last rule
        if !current_rule.is_empty() {
            rules.push(current_rule.trim().to_string());
        }

        // If no rules found, try to parse as single rule
        if rules.is_empty() && !yaml_content.trim().is_empty() {
            rules.push(yaml_content.trim().to_string());
        }

        Ok(rules)
    }

    /// Persist valid rules to output directory
    fn persist_rules(
        &self,
        rules: &[SemgrepRule],
        cwe: &str,
        language: &str,
    ) -> Result<(), RuleError> {
        let output_dir = PathBuf::from(&self.config.output_dir);
        std::fs::create_dir_all(&output_dir)
            .map_err(|e| RuleError::IoError(format!("Failed to create output directory: {}", e)))?;

        for (i, rule) in rules.iter().enumerate() {
            let filename = format!("{}_{}_{}.yml", cwe, language, i);
            let filepath = output_dir.join(&filename);

            std::fs::write(&filepath, &rule.yaml).map_err(|e| {
                RuleError::IoError(format!(
                    "Failed to write rule to {}: {}",
                    filepath.display(),
                    e
                ))
            })?;

            tracing::info!("Persisted rule: {}", filepath.display());
        }

        Ok(())
    }
}

/// Extract rule ID from YAML content
fn extract_rule_id(yaml: &str) -> Option<String> {
    for line in yaml.lines() {
        let trimmed = line.trim();
        if trimmed.contains("id:") {
            // Find the "id:" position and extract the value
            if let Some(idx) = trimmed.find("id:") {
                let after_id = &trimmed[idx + 3..];
                let id = after_id.trim();
                // Remove quotes if present
                let id = id.trim_matches('"').trim_matches('\'');
                if !id.is_empty() {
                    return Some(id.to_string());
                }
            }
        }
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_extract_rule_id() {
        let yaml = r#"rules:
  - id: test-rule-123
    patterns:
      - pattern: $X
    message: Test
    languages: [python]
    severity: WARNING
"#;
        assert_eq!(extract_rule_id(yaml), Some("test-rule-123".to_string()));
    }

    #[test]
    fn test_extract_rule_id_with_quotes() {
        let yaml = r#"rules:
  - id: "quoted-rule-456"
    patterns:
      - pattern: $X
    message: Test
    languages: [python]
    severity: WARNING
"#;
        assert_eq!(extract_rule_id(yaml), Some("quoted-rule-456".to_string()));
    }

    #[test]
    fn test_extract_rule_id_no_id() {
        let yaml = r#"rules:
  - patterns:
      - pattern: $X
    message: Test
    languages: [python]
    severity: WARNING
"#;
        assert_eq!(extract_rule_id(yaml), None);
    }
}
